import fs from "node:fs/promises";
const names = (await fs.readdir("src/art")).filter((name) => name.endsWith(".svg")).sort();
const entries = [];
for (const name of names)
  entries.push(
    `${JSON.stringify(name.slice(0, -4))}: ${JSON.stringify(await fs.readFile(`src/art/${name}`, "utf8"))}`,
  );
await fs.writeFile(
  "src/art/sprites_generated.ts",
  `// Generated by tools/build_svg_art.mjs.\nexport const sprites = {\n${entries.join(",\n")}\n};\nexport type SpriteName = keyof typeof sprites;\n`,
);
